2024-02-12 01:28:03,455 INFO commands
2024-02-12 01:28:03,691 INFO Start polling
2024-02-12 01:28:03,749 INFO Run polling for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:33:41,132 WARNING Received SIGINT signal
2024-02-12 01:33:41,133 INFO Polling stopped for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:33:41,133 INFO Polling stopped
2024-02-12 01:40:17,970 INFO commands
2024-02-12 01:40:18,130 INFO Start polling
2024-02-12 01:40:18,195 INFO Run polling for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:57:12,587 WARNING Received SIGINT signal
2024-02-12 01:57:12,587 INFO Polling stopped for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:57:12,588 INFO Polling stopped
2024-02-12 06:46:10,694 INFO commands
2024-02-12 06:46:11,017 INFO Start polling
2024-02-12 06:46:11,029 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-12 06:46:48,320 INFO Update id=471136450 is handled. Duration 237 ms by bot id=6443979698
2024-02-12 06:46:51,552 INFO Update id=471136451 is handled. Duration 33 ms by bot id=6443979698
2024-02-12 06:46:53,054 INFO Update id=471136452 is handled. Duration 108 ms by bot id=6443979698
2024-02-12 06:46:54,308 INFO Update id=471136453 is handled. Duration 111 ms by bot id=6443979698
2024-02-12 06:46:57,753 INFO Update id=471136454 is handled. Duration 376 ms by bot id=6443979698
2024-02-12 06:47:00,630 INFO Update id=471136455 is handled. Duration 445 ms by bot id=6443979698
2024-02-12 06:47:07,256 INFO Update id=471136456 is handled. Duration 319 ms by bot id=6443979698
2024-02-12 06:47:09,206 INFO Update id=471136457 is handled. Duration 465 ms by bot id=6443979698
2024-02-12 06:47:10,587 INFO Update id=471136458 is handled. Duration 65 ms by bot id=6443979698
2024-02-12 06:47:12,018 INFO Update id=471136459 is handled. Duration 147 ms by bot id=6443979698
2024-02-12 06:47:32,340 INFO Update id=471136460 is handled. Duration 253 ms by bot id=6443979698
2024-02-12 06:47:42,169 INFO Update id=471136461 is handled. Duration 8438 ms by bot id=6443979698
2024-02-12 06:49:51,542 INFO Update id=471136462 is handled. Duration 1277 ms by bot id=6443979698
2024-02-12 06:49:55,865 INFO Update id=471136463 is handled. Duration 48 ms by bot id=6443979698
2024-02-12 06:49:59,739 INFO Update id=471136464 is handled. Duration 40 ms by bot id=6443979698
2024-02-12 06:50:04,449 INFO Update id=471136465 is handled. Duration 38 ms by bot id=6443979698
2024-02-12 06:50:09,639 INFO Update id=471136466 is handled. Duration 1359 ms by bot id=6443979698
2024-02-12 06:50:11,373 ERROR RETRY [Errno 113] Connect call failed ('172.18.0.3', 5432)
Traceback (most recent call last):
  File "/bot/core/database/functions.py", line 18, in newfn
    return await func(*args, **kwargs)
  File "/bot/core/handlers/admin_handl.py", line 96, in get_files
    files_and_types = await get_watch_files_watch(watch_id)
  File "/bot/core/database/functions.py", line 271, in get_watch_files_watch
    res = await session.execute(query)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 455, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 200, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 941, in connect
    await_only(creator_fn(*arg, **kw)),
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 130, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 195, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('172.18.0.3', 5432)
2024-02-12 06:50:12,760 INFO Update id=471136467 is handled. Duration 1864 ms by bot id=6443979698
2024-02-12 06:50:16,388 INFO Update id=471136468 is handled. Duration 1341 ms by bot id=6443979698
2024-02-12 06:50:29,818 INFO Update id=471136469 is handled. Duration 1338 ms by bot id=6443979698
2024-02-12 06:50:31,870 INFO Update id=471136470 is handled. Duration 589 ms by bot id=6443979698
2024-02-12 06:50:33,170 INFO Update id=471136471 is handled. Duration 164 ms by bot id=6443979698
2024-02-12 06:50:34,507 INFO Update id=471136472 is handled. Duration 182 ms by bot id=6443979698
2024-02-12 06:50:39,082 INFO Update id=471136473 is handled. Duration 1139 ms by bot id=6443979698
2024-02-12 06:50:45,569 INFO Update id=471136474 is handled. Duration 5305 ms by bot id=6443979698
2024-02-12 06:58:49,608 INFO commands
2024-02-12 06:58:49,887 INFO Start polling
2024-02-12 06:58:49,895 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-12 07:00:36,719 INFO Update id=471136475 is handled. Duration 1323 ms by bot id=6443979698
2024-02-12 07:00:46,050 INFO Update id=471136476 is handled. Duration 96 ms by bot id=6443979698
2024-02-12 07:00:48,508 INFO Update id=471136477 is handled. Duration 125 ms by bot id=6443979698
2024-02-12 07:00:50,495 INFO Update id=471136478 is handled. Duration 280 ms by bot id=6443979698
2024-02-12 07:00:55,908 INFO Update id=471136479 is handled. Duration 1399 ms by bot id=6443979698
2024-02-12 07:00:57,702 INFO Update id=471136480 is handled. Duration 413 ms by bot id=6443979698
2024-02-12 07:01:03,221 INFO Update id=471136481 is handled. Duration 1693 ms by bot id=6443979698
2024-02-12 07:01:06,379 INFO Update id=471136482 is handled. Duration 1814 ms by bot id=6443979698
2024-02-12 07:01:07,795 INFO Update id=471136483 is handled. Duration 204 ms by bot id=6443979698
2024-02-12 07:01:09,172 INFO Update id=471136484 is handled. Duration 189 ms by bot id=6443979698
2024-02-12 07:01:13,840 INFO Update id=471136485 is handled. Duration 1183 ms by bot id=6443979698
2024-02-12 07:03:04,162 INFO Update id=471136486 is handled. Duration 109177 ms by bot id=6443979698
2024-02-12 08:18:37,296 INFO Update id=471136487 is handled. Duration 1232 ms by bot id=6443979698
2024-02-12 08:18:54,147 INFO Update id=471136488 is handled. Duration 1177 ms by bot id=6443979698
2024-02-12 08:18:59,600 INFO Update id=471136489 is handled. Duration 1177 ms by bot id=6443979698
2024-02-12 08:19:01,900 INFO Update id=471136490 is handled. Duration 203 ms by bot id=6443979698
2024-02-12 08:19:04,150 INFO Update id=471136491 is handled. Duration 32 ms by bot id=6443979698
2024-02-12 08:19:05,082 INFO Update id=471136492 is handled. Duration 34 ms by bot id=6443979698
2024-02-12 08:19:08,076 INFO Update id=471136493 is handled. Duration 416 ms by bot id=6443979698
2024-02-12 08:19:13,441 INFO Update id=471136494 is not handled. Duration 4 ms by bot id=6443979698
2024-02-12 08:19:20,941 INFO Update id=471136495 is handled. Duration 1560 ms by bot id=6443979698
2024-02-12 08:19:25,142 INFO Update id=471136496 is handled. Duration 1553 ms by bot id=6443979698
2024-02-12 08:19:28,928 INFO Update id=471136497 is handled. Duration 1473 ms by bot id=6443979698
2024-02-12 08:19:40,162 INFO Update id=471136498 is handled. Duration 381 ms by bot id=6443979698
2024-02-12 08:19:41,372 INFO Update id=471136499 is handled. Duration 54 ms by bot id=6443979698
2024-02-12 08:19:44,004 INFO Update id=471136500 is handled. Duration 1145 ms by bot id=6443979698
2024-02-12 08:22:10,116 INFO Update id=471136501 is handled. Duration 144218 ms by bot id=6443979698
2024-02-12 08:23:27,119 INFO Update id=471136502 is handled. Duration 1276 ms by bot id=6443979698
2024-02-12 08:23:56,099 INFO Update id=471136503 is handled. Duration 1374 ms by bot id=6443979698
2024-02-12 08:24:14,195 INFO Update id=471136504 is handled. Duration 3329 ms by bot id=6443979698
2024-02-12 08:24:23,158 INFO Update id=471136505 is handled. Duration 1258 ms by bot id=6443979698
2024-02-12 08:24:29,642 INFO Update id=471136506 is handled. Duration 1198 ms by bot id=6443979698
2024-02-12 08:24:40,399 INFO Update id=471136507 is handled. Duration 1448 ms by bot id=6443979698
2024-02-12 08:24:44,921 INFO Update id=471136508 is handled. Duration 1188 ms by bot id=6443979698
2024-02-12 08:24:56,837 INFO Update id=471136509 is handled. Duration 1182 ms by bot id=6443979698
2024-02-12 08:25:07,590 INFO Update id=471136510 is handled. Duration 52 ms by bot id=6443979698
2024-02-12 08:25:12,228 INFO Update id=471136511 is handled. Duration 157 ms by bot id=6443979698
2024-02-12 08:25:12,976 INFO Update id=471136512 is handled. Duration 78 ms by bot id=6443979698
2024-02-12 08:25:17,049 INFO Update id=471136513 is handled. Duration 1430 ms by bot id=6443979698
2024-02-12 08:25:22,098 INFO Update id=471136514 is handled. Duration 1445 ms by bot id=6443979698
2024-02-12 08:25:37,099 INFO Update id=471136515 is handled. Duration 1567 ms by bot id=6443979698
2024-02-12 08:25:42,176 INFO Update id=471136516 is handled. Duration 1711 ms by bot id=6443979698
2024-02-12 08:25:43,838 INFO Update id=471136517 is handled. Duration 224 ms by bot id=6443979698
2024-02-12 08:25:45,327 INFO Update id=471136518 is handled. Duration 227 ms by bot id=6443979698
2024-02-12 08:25:57,317 INFO Update id=471136519 is handled. Duration 1148 ms by bot id=6443979698
2024-02-12 08:32:14,988 INFO Update id=471136520 is handled. Duration 375661 ms by bot id=6443979698
2024-02-12 08:34:25,297 INFO Update id=471136521 is not handled. Duration 4 ms by bot id=6443979698
2024-02-12 08:34:34,311 INFO Update id=471136522 is not handled. Duration 7 ms by bot id=6443979698
2024-02-12 08:34:34,312 INFO Update id=471136523 is not handled. Duration 7 ms by bot id=6443979698
2024-02-12 08:34:42,113 INFO Update id=471136524 is handled. Duration 1240 ms by bot id=6443979698
2024-02-12 08:34:54,976 INFO Update id=471136525 is handled. Duration 160 ms by bot id=6443979698
2024-02-12 08:34:55,991 INFO Update id=471136526 is handled. Duration 1175 ms by bot id=6443979698
2024-02-12 08:34:59,890 INFO Update id=471136527 is handled. Duration 37 ms by bot id=6443979698
2024-02-12 08:35:03,772 INFO Update id=471136528 is handled. Duration 34 ms by bot id=6443979698
2024-02-12 08:35:05,165 INFO Update id=471136529 is handled. Duration 40 ms by bot id=6443979698
2024-02-12 08:35:08,041 INFO Update id=471136530 is handled. Duration 54 ms by bot id=6443979698
2024-02-12 08:35:12,072 INFO Update id=471136531 is handled. Duration 1742 ms by bot id=6443979698
2024-02-12 08:35:18,529 INFO Update id=471136532 is handled. Duration 1573 ms by bot id=6443979698
2024-02-12 08:36:31,361 INFO Update id=471136533 is handled. Duration 1540 ms by bot id=6443979698
2024-02-12 08:36:36,739 INFO Update id=471136534 is handled. Duration 1503 ms by bot id=6443979698
2024-02-12 08:36:43,481 INFO Update id=471136535 is handled. Duration 148 ms by bot id=6443979698
2024-02-12 08:36:44,820 INFO Update id=471136536 is handled. Duration 82 ms by bot id=6443979698
2024-02-12 08:36:53,135 INFO Update id=471136537 is handled. Duration 1171 ms by bot id=6443979698
2024-02-12 08:37:00,461 ERROR RETRY [Errno 113] Connect call failed ('172.18.0.3', 5432)
Traceback (most recent call last):
  File "/bot/core/database/functions.py", line 18, in newfn
    return await func(*args, **kwargs)
  File "/bot/core/database/functions.py", line 179, in get_watch_id
    res = await session.execute(query)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 455, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 200, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 941, in connect
    await_only(creator_fn(*arg, **kw)),
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 130, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 195, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('172.18.0.3', 5432)
2024-02-12 08:38:10,886 INFO Update id=471136538 is handled. Duration 76638 ms by bot id=6443979698
2024-02-12 08:38:29,783 INFO Update id=471136539 is handled. Duration 310 ms by bot id=6443979698
2024-02-12 08:38:33,664 INFO Update id=471136540 is handled. Duration 385 ms by bot id=6443979698
2024-02-12 08:39:31,570 INFO Update id=471136541 is handled. Duration 1161 ms by bot id=6443979698
2024-02-12 08:39:37,518 INFO Update id=471136542 is handled. Duration 1357 ms by bot id=6443979698
2024-02-12 14:18:31,811 INFO Update id=471136543 is handled. Duration 1808 ms by bot id=6443979698
2024-02-12 14:19:04,220 INFO Update id=471136544 is handled. Duration 3399 ms by bot id=6443979698
2024-02-12 14:20:20,768 INFO Update id=471136546 is handled. Duration 154 ms by bot id=6443979698
2024-02-12 14:20:25,154 INFO Update id=471136545 is handled. Duration 15580 ms by bot id=6443979698
2024-02-12 14:20:28,299 INFO Update id=471136547 is handled. Duration 109 ms by bot id=6443979698
2024-02-12 14:20:38,748 INFO Update id=471136548 is handled. Duration 79 ms by bot id=6443979698
2024-02-12 14:20:41,314 INFO Update id=471136549 is handled. Duration 146 ms by bot id=6443979698
2024-02-12 14:20:51,867 INFO Update id=471136550 is handled. Duration 697 ms by bot id=6443979698
2024-02-12 14:21:37,757 INFO Update id=471136551 is handled. Duration 2841 ms by bot id=6443979698
2024-02-12 14:22:16,366 INFO Update id=471136552 is handled. Duration 1566 ms by bot id=6443979698
2024-02-12 14:22:35,791 INFO Update id=471136553 is handled. Duration 1676 ms by bot id=6443979698
2024-02-12 14:22:49,101 INFO Update id=471136554 is handled. Duration 230 ms by bot id=6443979698
2024-02-12 14:22:51,318 INFO Update id=471136555 is handled. Duration 166 ms by bot id=6443979698
2024-02-12 14:23:21,828 INFO Update id=471136556 is handled. Duration 1227 ms by bot id=6443979698
2024-02-12 14:29:41,450 INFO Update id=471136557 is handled. Duration 366790 ms by bot id=6443979698
2024-02-12 14:30:11,670 INFO Update id=471136558 is handled. Duration 1601 ms by bot id=6443979698
2024-02-12 14:30:17,404 INFO Update id=471136559 is handled. Duration 1963 ms by bot id=6443979698
2024-02-12 14:30:19,612 INFO Update id=471136560 is handled. Duration 247 ms by bot id=6443979698
2024-02-12 14:30:21,537 INFO Update id=471136561 is handled. Duration 163 ms by bot id=6443979698
2024-02-12 14:30:27,270 INFO Update id=471136562 is handled. Duration 3437 ms by bot id=6443979698
2024-02-12 14:31:10,769 INFO Update id=471136563 is handled. Duration 40868 ms by bot id=6443979698
2024-02-13 13:39:32,040 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 13:39:32,040 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 13:39:43,059 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:03:06,333 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:03:06,334 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:03:17,352 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:03:17,354 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:03:17,354 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:03:28,374 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:50:11,713 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:50:11,713 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:50:22,734 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:54:02,992 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:54:02,992 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:54:14,017 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:59:04,171 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:59:04,171 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:59:15,189 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:02:15,295 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:02:15,295 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:02:26,313 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:10:06,588 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:10:06,589 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:10:17,622 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:14:17,909 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:14:17,909 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:14:28,929 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:22:09,303 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:22:09,303 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:22:20,479 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 09:42:19,095 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 09:42:19,095 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 09:42:30,115 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:15:50,250 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:15:50,250 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:16:01,265 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:18:21,330 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:18:21,331 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:18:32,510 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:18:32,512 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:18:32,512 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:18:43,529 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:20:33,607 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:20:33,607 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:20:44,624 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:22:04,742 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:22:04,742 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:22:15,759 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:23:45,842 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:23:45,842 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:23:56,864 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:25:36,973 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:25:36,973 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:25:47,987 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:25:47,989 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:25:47,989 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:25:59,008 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:27:19,498 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:27:19,498 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:27:30,522 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 23:16:15,226 INFO Setting commands to bot 1 1
2024-02-14 23:16:15,260 INFO Try to add an admin
2024-02-14 23:16:15,340 ERROR (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "user_tg_id_key"
DETAIL:  Key (tg_id)=(731253916) already exists.
[SQL: INSERT INTO "user" (tg_id, username, is_admin, registered_at) VALUES ($1::INTEGER, $2::VARCHAR, $3::BOOLEAN, $4::TIMESTAMP WITHOUT TIME ZONE) RETURNING "user".user_id]
[parameters: (731253916, 'MAIN_ADMIN', True, datetime.datetime(2024, 2, 14, 23, 16, 15, 335251))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-02-14 23:16:15,341 WARNING Admin already exists
2024-02-14 23:16:15,522 INFO Start polling
2024-02-14 23:16:15,531 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-14 23:17:22,940 INFO Setting commands to bot 1 1
2024-02-14 23:17:22,974 INFO Try to add an admin
2024-02-14 23:17:23,053 ERROR (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "user_tg_id_key"
DETAIL:  Key (tg_id)=(1146756342) already exists.
[SQL: INSERT INTO "user" (tg_id, username, is_admin, registered_at) VALUES ($1::INTEGER, $2::VARCHAR, $3::BOOLEAN, $4::TIMESTAMP WITHOUT TIME ZONE) RETURNING "user".user_id]
[parameters: (1146756342, 'MAIN_ADMIN', True, datetime.datetime(2024, 2, 14, 23, 17, 23, 46597))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-02-14 23:17:23,054 WARNING Admin already exists
2024-02-14 23:17:23,206 INFO Start polling
2024-02-14 23:17:23,213 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-14 23:17:28,625 INFO START 1146756342
2024-02-14 23:17:28,625 INFO Adiing user 1146756342
2024-02-14 23:17:28,800 INFO Succes [731253916, 1146756342]
2024-02-14 23:17:28,825 INFO Update id=471136564 is handled. Duration 202 ms by bot id=6443979698
2024-02-14 23:17:53,885 INFO Try to send new post 1146756342
2024-02-14 23:17:53,886 INFO Adiing user 1146756342
2024-02-14 23:17:54,025 INFO Succes [731253916, 1146756342]
2024-02-14 23:17:54,026 INFO user 1146756342 is admin
2024-02-14 23:17:54,057 INFO Update id=471136565 is handled. Duration 173 ms by bot id=6443979698
2024-02-14 23:18:00,340 INFO Getting channel post
2024-02-14 23:18:00,341 INFO Text for post тест
2024-02-14 23:18:00,384 INFO Update id=471136566 is handled. Duration 48 ms by bot id=6443979698
2024-02-14 23:18:02,313 INFO Price 1
2024-02-14 23:18:02,397 INFO Update id=471136567 is handled. Duration 89 ms by bot id=6443979698
2024-02-14 23:18:03,496 INFO Price 1
2024-02-14 23:18:03,644 INFO Update id=471136568 is handled. Duration 154 ms by bot id=6443979698
2024-02-14 23:18:06,098 INFO Name of watch тест
2024-02-14 23:18:06,119 INFO Check post before sendind
2024-02-14 23:18:06,120 INFO Inserting media {'unique_id': '11467563425804', 'message_text': 'тест', 'price': '1', 'price2': '1', 'name': 'тест'}
2024-02-14 23:18:06,269 INFO Getting text for watch 127
2024-02-14 23:18:06,341 INFO Get files for watch 127: []
2024-02-14 23:18:06,341 INFO Succes тест
2024-02-14 23:18:06,341 INFO Get files for watch 127: тест
2024-02-14 23:18:06,390 INFO Update id=471136569 is handled. Duration 295 ms by bot id=6443979698
2024-02-14 23:18:08,277 INFO Getting text for watch 127
2024-02-14 23:18:08,343 INFO Get files for watch 127: []
2024-02-14 23:18:08,343 INFO Succes тест
2024-02-14 23:18:08,344 INFO Get files for watch 127: тест
2024-02-14 23:18:08,397 INFO Upd mesg 127, 309
2024-02-14 23:18:08,515 INFO Update id=471136570 is handled. Duration 353 ms by bot id=6443979698
2024-02-14 23:19:28,823 INFO User 1146756342 choose watch 127
2024-02-14 23:19:28,824 INFO Adiing user 1146756342
2024-02-14 23:19:28,907 INFO Adiing user 1146756342
2024-02-14 23:19:28,974 INFO new order user 1146756342 watch: 127
2024-02-14 23:19:29,090 INFO Update id=471136571 is handled. Duration 267 ms by bot id=6443979698
2024-02-14 23:19:41,881 INFO Check user order  1146756342
2024-02-14 23:19:41,882 INFO Get watch status
2024-02-14 23:19:41,949 INFO watch status 1146756342 for_sale
2024-02-14 23:19:41,952 INFO Get book2: yes_to_pay 1146756342
2024-02-14 23:19:42,026 INFO Succes 127
2024-02-14 23:19:42,109 INFO Getting text for watch 127
2024-02-14 23:19:42,180 INFO Get files for watch 127: []
2024-02-14 23:19:42,180 INFO Succes тест
2024-02-14 23:19:42,226 INFO Update id=471136572 is handled. Duration 381 ms by bot id=6443979698
2024-02-14 23:19:43,570 INFO Watch: book 1146756342
2024-02-14 23:19:43,621 INFO Update id=471136573 is handled. Duration 54 ms by bot id=6443979698
2024-02-14 23:19:45,147 INFO Watch: erc20 1146756342
2024-02-14 23:19:45,187 INFO Update id=471136574 is handled. Duration 42 ms by bot id=6443979698
2024-02-14 23:21:45,173 INFO Watch addres: 0x0261036567Bf14666C67a35C2A204eb302E11D85 1146756342
2024-02-14 23:21:45,174 INFO Setting pay params user: 1146756342 {'book_or_buy': 'book', 'network': 'erc20', 'address': '0x0261036567Bf14666C67a35C2A204eb302E11D85'}
2024-02-14 23:21:45,274 INFO Update id=471136575 is handled. Duration 103 ms by bot id=6443979698
2024-02-14 23:21:57,461 INFO Continue booking 1146756342
2024-02-14 23:21:57,571 INFO Making hash 1146756342 {'book_or_buy': 'book', 'network': 'erc20', 'address': '0x0261036567Bf14666C67a35C2A204eb302E11D85', 'price': 1}
2024-02-14 23:21:57,572 INFO Requsting qrcode {'payerAddress': '0x0261036567Bf14666C67a35C2A204eb302E11D85', 'amount': 1, 'network': 'erc20', 'webhookUrl': 'http://fastapi_app:8000/webhook/1146756342', 'payment_type': 'investment', 'hash': '62a639e6f5a606c6ca90a1c2876a7881'}
2024-02-14 23:21:57,577 INFO Qrcode status code: 403
2024-02-14 23:21:57,622 INFO Update id=471136576 is handled. Duration 163 ms by bot id=6443979698
2024-02-14 23:24:11,220 INFO Setting commands to bot 1 1
2024-02-14 23:24:11,252 INFO Try to add an admin
2024-02-14 23:24:11,323 ERROR (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "user_tg_id_key"
DETAIL:  Key (tg_id)=(1146756342) already exists.
[SQL: INSERT INTO "user" (tg_id, username, is_admin, registered_at) VALUES ($1::INTEGER, $2::VARCHAR, $3::BOOLEAN, $4::TIMESTAMP WITHOUT TIME ZONE) RETURNING "user".user_id]
[parameters: (1146756342, 'MAIN_ADMIN', True, datetime.datetime(2024, 2, 14, 23, 24, 11, 318055))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-02-14 23:24:11,323 WARNING Admin already exists
2024-02-14 23:24:11,460 INFO Start polling
2024-02-14 23:24:11,470 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-14 23:24:11,500 INFO Update id=471136577 is not handled. Duration 2 ms by bot id=6443979698
2024-02-14 23:24:29,731 INFO User 1146756342 choose watch 127
2024-02-14 23:24:29,732 INFO Adiing user 1146756342
2024-02-14 23:24:29,845 INFO Adiing user 1146756342
2024-02-14 23:24:29,905 INFO new order user 1146756342 watch: 127
2024-02-14 23:24:30,000 INFO Update id=471136578 is handled. Duration 269 ms by bot id=6443979698
2024-02-14 23:24:34,058 INFO Check user order  1146756342
2024-02-14 23:24:34,058 INFO Get watch status
2024-02-14 23:24:34,126 INFO watch status 1146756342 for_sale
2024-02-14 23:24:34,131 INFO Get book2: yes_to_pay 1146756342
2024-02-14 23:24:34,215 INFO Succes 127
2024-02-14 23:24:34,304 INFO Getting text for watch 127
2024-02-14 23:24:34,393 INFO Get files for watch 127: []
2024-02-14 23:24:34,394 INFO Succes тест
2024-02-14 23:24:34,446 INFO Update id=471136579 is handled. Duration 454 ms by bot id=6443979698
2024-02-14 23:24:35,850 INFO Watch: book 1146756342
2024-02-14 23:24:35,890 INFO Update id=471136580 is handled. Duration 43 ms by bot id=6443979698
2024-02-14 23:24:37,087 INFO Watch: erc20 1146756342
2024-02-14 23:24:37,138 INFO Update id=471136581 is handled. Duration 53 ms by bot id=6443979698
2024-02-14 23:24:52,193 INFO Watch addres: 0x0261036567Bf14666C67a35C2A204eb302E11D85 1146756342
2024-02-14 23:24:52,194 INFO Setting pay params user: 1146756342 {'book_or_buy': 'book', 'network': 'erc20', 'address': '0x0261036567Bf14666C67a35C2A204eb302E11D85'}
2024-02-14 23:24:52,311 INFO Update id=471136582 is handled. Duration 120 ms by bot id=6443979698
2024-02-14 23:24:54,161 INFO Continue booking 1146756342
2024-02-14 23:24:54,218 INFO Making hash 1146756342 {'book_or_buy': 'book', 'network': 'erc20', 'address': '0x0261036567Bf14666C67a35C2A204eb302E11D85', 'price': 1}
2024-02-14 23:24:54,219 INFO Requsting qrcode {'payerAddress': '0x0261036567Bf14666C67a35C2A204eb302E11D85', 'amount': 1, 'network': 'erc20', 'webhookUrl': 'http://fastapi_app:8000/webhook/1146756342', 'payment_type': 'investment', 'hash': '17ea449b04a3bb8cd2adfe0ba9ae0a3e'}
2024-02-14 23:24:54,582 INFO Qrcode status code: 201
2024-02-14 23:24:54,582 INFO Sending qr: {'depositAddress': '0xB108F7609c35d5B1d1bfEaB0789534DA5e748bAd', 'amount': 1, 'network': 'erc20', 'id': '1707953094415', 'payment_type': 'investment', 'qrCode': '                                     \n                                     \n    █▀▀▀▀▀█  ▀ █▄▀▄▀█ ▀ ▀ █▀▀▀▀▀█    \n    █ ███ █ █▄█ ▄ ▀▀▀▄ ▀▀ █ ███ █    \n    █ ▀▀▀ █ ███▄▀█▄██ █▀▀ █ ▀▀▀ █    \n    ▀▀▀▀▀▀▀ █ █ █ ▀▄▀ ▀▄▀ ▀▀▀▀▀▀▀    \n    █ █▀██▀ ▄ █ ▀▄▄▄█ ▄▄▄ █▀█▀▀ ▄    \n    █  ▀  ▀▄  ▄ ▀▄ ██▀█ ▀▀▄▀▄▀ █▄    \n    ▀▄▄ ▀▄▀▄█▄▄ ▄ ▄▄▄ ▀▄▀▀▄▄▄▀▀█     \n    ▄▄▄▄ ▄▀▄ ▄ ▀   █  █ ▄  ▀▀  ▄     \n    ▄▀▄▄█▄▀▄ ██▀▀▄██▀▄▀▄▄▄▄▀▄▀█▀█    \n    █ ▄█▀▀▀ ▄▀▄▄█ ▄█▀ ▄ ▀▄  █▄ ▄     \n    ▀  ▀  ▀▀▄▀▀▄   █▀▄▄▄█▀▀▀█▄ ▀▄    \n    █▀▀▀▀▀█ ▄▀▄▄█    █▄▀█ ▀ █ ▀▀     \n    █ ███ █ █▀█▄   █ █▄ ██▀█▀█▀▀▀    \n    █ ▀▀▀ █ ▀  █▄▀ █▀▀▄   ▀ ▀▀▀█     \n    ▀▀▀▀▀▀▀ ▀ ▀  ▀ ▀▀  ▀   ▀▀▀▀      \n                                     \n                                     '}
2024-02-14 23:24:54,647 INFO Succes 127
2024-02-14 23:24:54,837 INFO Updating status tg:1146756342 watch: 127 status: booking
2024-02-14 23:24:54,917 INFO Succes True
2024-02-14 23:24:54,918 INFO Creating qr 127
2024-02-14 23:24:55,045 INFO Polling for watch: 127 user: 1146756342
2024-02-14 23:26:48,647 INFO Getting logs 1146756342
2024-02-14 23:26:48,647 INFO Adiing user 1146756342
2024-02-14 23:26:48,776 INFO Succes [731253916, 1146756342]
2024-02-14 23:26:48,820 WARNING user 1146756342 is not admin
2024-02-14 23:26:48,821 INFO Update id=471136584 is handled. Duration 176 ms by bot id=6443979698
2024-02-14 23:29:59,425 INFO Poling ended watch: 127 user: 1146756342 False False False
2024-02-14 23:29:59,449 INFO Updating status tg:1146756342 watch: 127 status: for_sale
2024-02-14 23:29:59,518 INFO Succes True
2024-02-14 23:29:59,566 INFO Reset all data for watch: 127
2024-02-14 23:29:59,566 INFO Update id=471136583 is handled. Duration 305408 ms by bot id=6443979698
2024-02-15 15:14:05,953 INFO Getting logs 731253916
2024-02-15 15:14:05,954 INFO Adiing user 731253916
2024-02-15 15:14:06,108 INFO Succes [1146756342, 731253916]
2024-02-15 15:14:06,582 WARNING user 731253916 is not admin
2024-02-15 15:14:06,582 INFO Update id=471136585 is handled. Duration 630 ms by bot id=6443979698
2024-02-15 23:58:57,026 ERROR Failed to fetch updates - TelegramRetryAfter: Telegram server says - Flood control exceeded on method 'GetUpdates'. Retry in 5 seconds.
Original description: Too Many Requests: retry after 5
(background on this error at: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)
2024-02-15 23:58:57,027 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-15 23:58:58,031 ERROR Failed to fetch updates - TelegramServerError: Telegram server says - Bad Gateway
2024-02-15 23:58:58,031 WARNING Sleep for 1.429860 seconds and try again... (tryings = 1, bot id = 6443979698)
2024-02-15 23:58:59,466 ERROR Failed to fetch updates - TelegramServerError: Telegram server says - Bad Gateway
2024-02-15 23:58:59,466 WARNING Sleep for 1.837595 seconds and try again... (tryings = 2, bot id = 6443979698)
2024-02-15 23:59:30,952 INFO Connection established (tryings = 3, bot id = 6443979698)
2024-02-16 00:11:21,393 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-16 00:11:21,393 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-16 00:11:32,410 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-17 21:49:14,802 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-17 21:49:14,802 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-17 21:49:25,818 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-17 22:09:16,397 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-17 22:09:16,398 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-17 22:09:27,414 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-17 22:09:27,416 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-17 22:09:27,416 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-17 22:09:38,432 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-17 22:11:38,488 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-17 22:11:38,488 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-17 22:11:49,506 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-17 22:15:49,746 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-17 22:15:49,747 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-17 22:16:00,765 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-19 20:52:36,124 INFO START 731253916
2024-02-19 20:52:36,124 INFO Adiing user 731253916
2024-02-19 20:52:36,305 INFO Succes [1146756342, 731253916]
2024-02-19 20:52:36,376 INFO Update id=471136586 is handled. Duration 252 ms by bot id=6443979698
2024-02-19 20:52:49,937 INFO Try to send new post 731253916
2024-02-19 20:52:49,937 INFO Adiing user 731253916
2024-02-19 20:52:50,081 INFO Succes [1146756342, 731253916]
2024-02-19 20:52:50,081 INFO user 731253916 is admin
2024-02-19 20:52:50,226 INFO Update id=471136587 is handled. Duration 291 ms by bot id=6443979698
2024-02-19 20:53:04,703 INFO Getting channel post
2024-02-19 20:53:04,849 INFO Update id=471136588 is handled. Duration 148 ms by bot id=6443979698
2024-02-19 20:53:15,708 INFO Getting channel post
2024-02-19 20:53:15,708 INFO Text for post 1 бакс и диплом ваш
2024-02-19 20:53:15,746 INFO Update id=471136589 is handled. Duration 39 ms by bot id=6443979698
2024-02-19 20:53:18,006 INFO Price 1
2024-02-19 20:53:18,069 INFO Update id=471136590 is handled. Duration 65 ms by bot id=6443979698
2024-02-19 20:53:19,142 INFO Price 1
2024-02-19 20:53:19,176 INFO Update id=471136591 is handled. Duration 36 ms by bot id=6443979698
2024-02-19 20:53:21,662 INFO Name of watch ппппп
2024-02-19 20:53:21,717 INFO Check post before sendind
2024-02-19 20:53:21,717 INFO Inserting media {'unique_id': '7312539165847', 'message_text': '1 бакс и диплом ваш', 'price': '1', 'price2': '1', 'name': 'ппппп'}
2024-02-19 20:53:21,856 INFO Getting text for watch 128
2024-02-19 20:53:21,921 INFO Get files for watch 128: [('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', datetime.datetime(2024, 2, 19, 20, 53, 4, 841141))]
2024-02-19 20:53:21,921 INFO Succes ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 20:53:21,921 INFO Get files for watch 128: ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 20:53:22,007 INFO Update id=471136592 is handled. Duration 348 ms by bot id=6443979698
2024-02-19 20:53:25,868 INFO Getting text for watch 128
2024-02-19 20:53:25,937 INFO Get files for watch 128: [('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', datetime.datetime(2024, 2, 19, 20, 53, 4, 841141))]
2024-02-19 20:53:25,938 INFO Succes ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 20:53:25,938 INFO Get files for watch 128: ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 20:53:26,043 INFO Upd mesg 128, 310
2024-02-19 20:53:26,189 INFO Update id=471136593 is handled. Duration 510 ms by bot id=6443979698
2024-02-19 20:53:55,820 INFO User 731253916 choose watch 127
2024-02-19 20:53:55,821 INFO Adiing user 731253916
2024-02-19 20:53:55,952 INFO Adiing user 731253916
2024-02-19 20:53:56,021 INFO new order user 731253916 watch: 127
2024-02-19 20:53:56,190 INFO Update id=471136594 is handled. Duration 370 ms by bot id=6443979698
2024-02-19 20:54:00,784 INFO no to pay 731253916
2024-02-19 20:54:00,804 INFO Update id=471136595 is handled. Duration 21 ms by bot id=6443979698
2024-02-19 20:54:33,400 INFO User 401078294 choose watch 128
2024-02-19 20:54:33,400 INFO Adiing user 401078294
2024-02-19 20:54:33,513 INFO Adiing user 401078294
2024-02-19 20:54:33,592 INFO new order user 401078294 watch: 128
2024-02-19 20:54:33,699 INFO Update id=471136596 is not handled. Duration 299 ms by bot id=6443979698
2024-02-19 20:54:33,699 ERROR Cause exception while process update id=471136596 by bot id=6443979698
TelegramForbiddenError: Telegram server says - Forbidden: bot can't initiate conversation with a user
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/bot/core/handlers/base_handlers.py", line 178, in book_from_channel
    await bot.send_message(call.from_user.id, "Вы выбрали новый товар. Перейти к оплате?", reply_markup=get_kb({"Да": "yes_to_pay", "Нет": "no_to_pay"}, [2]))
  File "/usr/local/lib/python3.9/site-packages/aiogram/client/bot.py", line 2766, in send_message
    return await self(call, request_timeout=request_timeout)
  File "/usr/local/lib/python3.9/site-packages/aiogram/client/bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/usr/local/lib/python3.9/site-packages/aiogram/client/session/base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/usr/local/lib/python3.9/site-packages/aiogram/client/session/aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "/usr/local/lib/python3.9/site-packages/aiogram/client/session/base.py", line 128, in check_response
    raise TelegramForbiddenError(method=method, message=description)
aiogram.exceptions.TelegramForbiddenError: Telegram server says - Forbidden: bot can't initiate conversation with a user
2024-02-19 20:54:38,627 INFO START 401078294
2024-02-19 20:54:38,627 INFO Adiing user 401078294
2024-02-19 20:54:38,789 INFO Succes [1146756342, 731253916]
2024-02-19 20:54:38,821 INFO Update id=471136597 is not handled. Duration 195 ms by bot id=6443979698
2024-02-19 20:54:38,821 ERROR Cause exception while process update id=471136597 by bot id=6443979698
AttributeError: module 'logging' has no attribute 'infp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/bot/core/handlers/base_handlers.py", line 88, in start
    logging.infp(f"Checking orders of user {message.from_user.id}")
AttributeError: module 'logging' has no attribute 'infp'
2024-02-19 20:55:02,187 INFO Getting logs 731253916
2024-02-19 20:55:02,188 INFO Adiing user 731253916
2024-02-19 20:55:02,393 INFO Succes [1146756342, 731253916]
2024-02-19 20:55:02,478 WARNING user 731253916 is not admin
2024-02-19 20:55:02,479 INFO Update id=471136598 is handled. Duration 295 ms by bot id=6443979698
2024-02-19 20:56:12,153 INFO User 731253916 choose watch 128
2024-02-19 20:56:12,154 INFO Adiing user 731253916
2024-02-19 20:56:12,298 INFO Adiing user 731253916
2024-02-19 20:56:12,370 INFO new order user 731253916 watch: 128
2024-02-19 20:56:12,481 INFO Update id=471136599 is handled. Duration 329 ms by bot id=6443979698
2024-02-19 20:56:19,409 INFO no to pay 731253916
2024-02-19 20:56:19,436 INFO Update id=471136600 is handled. Duration 27 ms by bot id=6443979698
2024-02-19 21:01:59,101 INFO BOOK 401078294
2024-02-19 21:01:59,104 INFO Adiing user 401078294
2024-02-19 21:01:59,222 INFO Check user order  401078294
2024-02-19 21:01:59,222 INFO Get watch status
2024-02-19 21:01:59,285 INFO watch status 401078294 for_sale
2024-02-19 21:01:59,288 INFO Get book
2024-02-19 21:01:59,350 INFO Succes 128
2024-02-19 21:01:59,413 INFO Getting text for watch 128
2024-02-19 21:01:59,478 INFO Get files for watch 128: [('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', datetime.datetime(2024, 2, 19, 20, 53, 4, 841141))]
2024-02-19 21:01:59,478 INFO Succes ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 21:01:59,587 INFO Update id=471136601 is handled. Duration 487 ms by bot id=6443979698
2024-02-19 21:02:41,146 INFO Watch: buy 401078294
2024-02-19 21:02:41,327 INFO Update id=471136602 is handled. Duration 183 ms by bot id=6443979698
2024-02-19 21:02:54,583 INFO User 401078294 choose watch 128
2024-02-19 21:02:54,583 INFO Adiing user 401078294
2024-02-19 21:02:54,681 INFO Adiing user 401078294
2024-02-19 21:02:54,749 INFO new order user 401078294 watch: 128
2024-02-19 21:02:54,859 INFO Update id=471136603 is handled. Duration 276 ms by bot id=6443979698
2024-02-19 21:02:58,598 INFO Check user order  401078294
2024-02-19 21:02:58,598 INFO Get watch status
2024-02-19 21:02:58,664 INFO watch status 401078294 for_sale
2024-02-19 21:02:58,667 INFO Get book2: yes_to_pay 401078294
2024-02-19 21:02:58,735 INFO Succes 128
2024-02-19 21:02:58,805 INFO Getting text for watch 128
2024-02-19 21:02:58,878 INFO Get files for watch 128: [('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', datetime.datetime(2024, 2, 19, 20, 53, 4, 841141))]
2024-02-19 21:02:58,879 INFO Succes ('AgACAgIAAxkBAAIW2WXTv7B09qqtKSRwFCcvo_dxl9Q_AAIZ0zEb9rmgSssmxkeDI48LAQADAgADeQADNAQ', 'photo', '1 бакс и диплом ваш')
2024-02-19 21:02:58,947 INFO Update id=471136604 is handled. Duration 399 ms by bot id=6443979698
2024-02-19 21:03:01,496 INFO Watch: buy 401078294
2024-02-19 21:03:01,772 INFO Update id=471136605 is handled. Duration 278 ms by bot id=6443979698
2024-02-19 21:03:04,273 INFO Watch: trc20 401078294
2024-02-19 21:03:04,319 INFO Update id=471136606 is handled. Duration 49 ms by bot id=6443979698
2024-02-19 21:03:15,802 INFO Watch addres: TYbTtjR8WJkqqBdWm21sQgXxTBL8MxAPPr 401078294
2024-02-19 21:03:15,802 INFO Setting pay params user: 401078294 {'book_or_buy': 'buy', 'network': 'trc20', 'address': 'TYbTtjR8WJkqqBdWm21sQgXxTBL8MxAPPr'}
2024-02-19 21:03:15,899 INFO Update id=471136607 is handled. Duration 101 ms by bot id=6443979698
2024-02-19 21:03:27,925 INFO Continue booking 401078294
2024-02-19 21:03:27,966 INFO Making hash 401078294 {'book_or_buy': 'buy', 'network': 'trc20', 'address': 'TYbTtjR8WJkqqBdWm21sQgXxTBL8MxAPPr', 'price': 1}
2024-02-19 21:03:27,968 INFO Requsting qrcode {'payerAddress': 'TYbTtjR8WJkqqBdWm21sQgXxTBL8MxAPPr', 'amount': 1, 'network': 'trc20', 'webhookUrl': 'http://fastapi_app:8000/webhook/401078294', 'payment_type': 'investment', 'hash': '93c12291aa0966eef309b2ecc6d072b1'}
2024-02-19 21:03:29,665 INFO Qrcode status code: 201
2024-02-19 21:03:29,666 INFO Sending qr: {'depositAddress': 'TYxaEiqgusQtxcLPagc8quELX97o7kndY6', 'amount': 1, 'network': 'trc20', 'id': '1708376609570', 'payment_type': 'investment', 'qrCode': '                                     \n                                     \n    █▀▀▀▀▀█  █▄ ▄███▄ ▀ █ █▀▀▀▀▀█    \n    █ ███ █ █ █▀█▀▄█    █ █ ███ █    \n    █ ▀▀▀ █ ██ ▀▀  ▀▀▀▀▀█ █ ▀▀▀ █    \n    ▀▀▀▀▀▀▀ █▄▀ ▀ █ █ █ ▀ ▀▀▀▀▀▀▀    \n    ▀ ████▀▄▄██▀▄▄▄▄ ▄ ▄█ ███▀▀▄▄    \n    ▄▀▄▄▀▀▀▀▄▀▄█▄█▀▀▄ █  █▀▄██ ▄     \n      ▄▀▄█▀ ▀ ▀▄█ ▀▀▀█▀█▀▄▄█▄▄ ▀█    \n    ▄█ ▄ █▀▀▄     ▄█▀ ▀▄▀▀▄▀██       \n    █▄▀█▄▄▀▄██ ▄ ▄▄▄█▀▀▄▄▄ ██ █▀▀    \n    █ █▀█▄▀▀▄▄▀  █▀█▄▀ ▄█▄▀▀▄█ ▄     \n    ▀  ▀▀ ▀▀█▀▀█▀ ▀▀▄█▄ █▀▀▀█▀▀      \n    █▀▀▀▀▀█ ▄▀▄█  ▄▀▄▀ ██ ▀ ██ ▄▄    \n    █ ███ █ █▀██ ▄▄ ▄▀▀▄▀▀▀█▀▄▀█▄    \n    █ ▀▀▀ █ ▀▄█ █▄ ▀▀▀  ▄▄ ███▀█     \n    ▀▀▀▀▀▀▀ ▀▀ ▀     ▀ ▀ ▀ ▀▀▀▀      \n                                     \n                                     '}
2024-02-19 21:03:29,733 INFO Succes 128
2024-02-19 21:03:29,829 INFO Updating status tg:401078294 watch: 128 status: booking
2024-02-19 21:03:29,901 INFO Succes True
2024-02-19 21:03:29,901 INFO Creating qr 128
2024-02-19 21:03:30,021 INFO Polling for watch: 128 user: 401078294
2024-02-19 21:08:34,564 INFO Poling ended watch: 128 user: 401078294 False False False
2024-02-19 21:08:34,593 INFO Updating status tg:401078294 watch: 128 status: for_sale
2024-02-19 21:08:34,662 INFO Succes True
2024-02-19 21:08:34,794 INFO Reset all data for watch: 128
2024-02-19 21:08:34,794 INFO Update id=471136608 is handled. Duration 306873 ms by bot id=6443979698
2024-02-19 22:17:12,124 INFO Setting commands to bot 1 1
2024-02-19 22:17:12,175 INFO Try to add an admin
2024-02-19 22:17:12,249 ERROR (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "user_tg_id_key"
DETAIL:  Key (tg_id)=(1146756342) already exists.
[SQL: INSERT INTO "user" (tg_id, username, is_admin, registered_at) VALUES ($1::INTEGER, $2::VARCHAR, $3::BOOLEAN, $4::TIMESTAMP WITHOUT TIME ZONE) RETURNING "user".user_id]
[parameters: (1146756342, 'MAIN_ADMIN', True, datetime.datetime(2024, 2, 19, 22, 17, 12, 242455))]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-02-19 22:17:12,250 WARNING Admin already exists
2024-02-19 22:17:12,463 INFO Start polling
2024-02-19 22:17:12,475 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-19 22:21:24,450 INFO Setting commands to bot 1 1
2024-02-19 22:21:24,482 INFO Try to add an admin
2024-02-19 22:21:24,578 WARNING Admin 1146756342 already exists
2024-02-19 22:21:24,767 INFO Start polling
2024-02-19 22:21:24,780 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-19 22:21:24,833 INFO Getting logs 1146756342
2024-02-19 22:21:24,834 INFO Adiing user 1146756342
2024-02-19 22:21:24,980 INFO Succes [1146756342, 731253916]
2024-02-19 22:21:25,066 WARNING user 1146756342 is not admin
2024-02-19 22:21:25,067 INFO Update id=471136609 is handled. Duration 236 ms by bot id=6443979698
2024-02-19 22:27:07,161 INFO Webhook received {'sdvsvd': 'sdcsdvsdv'}
2024-02-19 22:27:26,253 INFO Getting logs 1146756342
2024-02-19 22:27:26,253 INFO Adiing user 1146756342
2024-02-19 22:27:26,415 INFO Succes [1146756342, 731253916]
2024-02-19 22:27:26,494 WARNING user 1146756342 is not admin
2024-02-19 22:27:26,494 INFO Update id=471136610 is handled. Duration 244 ms by bot id=6443979698
2024-02-19 22:29:37,109 INFO Setting commands to bot
2024-02-19 22:29:37,222 INFO Try to add an admin
2024-02-19 22:29:37,292 WARNING Admin 1146756342 already exists
2024-02-19 22:29:37,456 INFO Start polling
2024-02-19 22:29:37,470 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-19 22:29:44,237 INFO Webhook received {'sdvsvd': 'sdcsdvsdv'}
2024-02-19 22:38:58,663 INFO Setting commands to bot
2024-02-19 22:38:58,698 INFO Try to add an admin
2024-02-19 22:38:58,779 WARNING Admin 1146756342 already exists
2024-02-19 22:38:58,940 INFO Start polling
2024-02-19 22:38:58,949 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-19 22:42:39,588 INFO Setting commands to bot
2024-02-19 22:42:39,621 INFO Try to add an admin
2024-02-19 22:42:39,699 WARNING Admin 1146756342 already exists
2024-02-19 22:42:39,859 INFO Start polling
2024-02-19 22:42:39,869 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-19 22:42:45,352 INFO START 1146756342
2024-02-19 22:42:45,353 INFO Adiing user 1146756342
2024-02-19 22:42:45,522 INFO Succes [1146756342, 731253916]
2024-02-19 22:42:45,556 INFO Update id=471136611 is handled. Duration 205 ms by bot id=6443979698
2024-02-19 22:42:52,525 INFO Getting logs 1146756342
2024-02-19 22:42:52,525 INFO Adiing user 1146756342
2024-02-19 22:42:52,668 INFO Succes [1146756342, 731253916]
2024-02-19 22:42:52,719 WARNING user 1146756342 is not admin
2024-02-19 22:42:52,720 INFO Update id=471136612 is handled. Duration 197 ms by bot id=6443979698
2024-02-20 09:46:15,677 INFO Getting logs 731253916
2024-02-20 09:46:15,677 INFO Adiing user 731253916
2024-02-20 09:46:15,819 INFO Succes [1146756342, 731253916]
2024-02-20 09:46:15,960 WARNING user 731253916 is not admin
2024-02-20 09:46:15,960 INFO Update id=471136613 is handled. Duration 284 ms by bot id=6443979698
2024-02-22 04:42:40,435 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-22 04:42:40,435 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-22 04:42:51,452 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-25 01:10:22,710 ERROR Failed to fetch updates - TelegramServerError: Telegram server says - Bad Gateway
2024-02-25 01:10:22,711 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-25 01:10:23,717 ERROR Failed to fetch updates - TelegramServerError: Telegram server says - Bad Gateway
2024-02-25 01:10:23,717 WARNING Sleep for 1.566497 seconds and try again... (tryings = 1, bot id = 6443979698)
2024-02-25 01:10:49,628 INFO Connection established (tryings = 2, bot id = 6443979698)
2024-02-26 06:40:58,326 INFO START 308912114
2024-02-26 06:40:58,326 INFO Adiing user 308912114
2024-02-26 06:40:58,507 INFO Succes [1146756342, 731253916]
2024-02-26 06:40:58,534 INFO Checking orders of user 308912114
2024-02-26 06:40:58,534 INFO Get watch status
2024-02-26 06:40:58,606 INFO watch status 308912114 no order
2024-02-26 06:40:58,659 INFO Update id=471136614 is handled. Duration 335 ms by bot id=6443979698
2024-02-26 20:05:16,835 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-26 20:05:16,835 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-26 20:05:27,857 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-27 09:32:09,814 INFO START 1146756342
2024-02-27 09:32:09,814 INFO Adiing user 1146756342
2024-02-27 09:32:10,000 INFO Succes [731253916, 1146756342]
2024-02-27 09:32:10,030 INFO Update id=471136615 is handled. Duration 217 ms by bot id=6443979698
2024-02-27 10:16:41,148 INFO Setting commands to bot
2024-02-27 10:16:41,187 INFO Try to add an admin
2024-02-27 10:16:41,266 WARNING Admin 1146756342 already exists
2024-02-27 10:16:41,458 INFO Start polling
2024-02-27 10:16:41,467 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-27 10:19:48,754 INFO INVITED TO CHAT: -1002114833459
2024-02-27 10:19:48,754 INFO Update id=471136616 is handled. Duration 0 ms by bot id=6443979698
2024-02-27 10:20:10,070 INFO INVITED TO CHAT: -1002114833459
2024-02-27 10:20:10,071 INFO Update id=471136617 is handled. Duration 0 ms by bot id=6443979698
2024-02-27 10:21:05,721 INFO INVITED TO CHAT: -1002114833459
2024-02-27 10:21:05,722 INFO Update id=471136618 is handled. Duration 0 ms by bot id=6443979698
