2024-02-12 01:28:03,455 INFO commands
2024-02-12 01:28:03,691 INFO Start polling
2024-02-12 01:28:03,749 INFO Run polling for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:33:41,132 WARNING Received SIGINT signal
2024-02-12 01:33:41,133 INFO Polling stopped for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:33:41,133 INFO Polling stopped
2024-02-12 01:40:17,970 INFO commands
2024-02-12 01:40:18,130 INFO Start polling
2024-02-12 01:40:18,195 INFO Run polling for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:57:12,587 WARNING Received SIGINT signal
2024-02-12 01:57:12,587 INFO Polling stopped for bot @Cutest_test_bot id=6201193657 - 'CuteTestBot'
2024-02-12 01:57:12,588 INFO Polling stopped
2024-02-12 06:46:10,694 INFO commands
2024-02-12 06:46:11,017 INFO Start polling
2024-02-12 06:46:11,029 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-12 06:46:48,320 INFO Update id=471136450 is handled. Duration 237 ms by bot id=6443979698
2024-02-12 06:46:51,552 INFO Update id=471136451 is handled. Duration 33 ms by bot id=6443979698
2024-02-12 06:46:53,054 INFO Update id=471136452 is handled. Duration 108 ms by bot id=6443979698
2024-02-12 06:46:54,308 INFO Update id=471136453 is handled. Duration 111 ms by bot id=6443979698
2024-02-12 06:46:57,753 INFO Update id=471136454 is handled. Duration 376 ms by bot id=6443979698
2024-02-12 06:47:00,630 INFO Update id=471136455 is handled. Duration 445 ms by bot id=6443979698
2024-02-12 06:47:07,256 INFO Update id=471136456 is handled. Duration 319 ms by bot id=6443979698
2024-02-12 06:47:09,206 INFO Update id=471136457 is handled. Duration 465 ms by bot id=6443979698
2024-02-12 06:47:10,587 INFO Update id=471136458 is handled. Duration 65 ms by bot id=6443979698
2024-02-12 06:47:12,018 INFO Update id=471136459 is handled. Duration 147 ms by bot id=6443979698
2024-02-12 06:47:32,340 INFO Update id=471136460 is handled. Duration 253 ms by bot id=6443979698
2024-02-12 06:47:42,169 INFO Update id=471136461 is handled. Duration 8438 ms by bot id=6443979698
2024-02-12 06:49:51,542 INFO Update id=471136462 is handled. Duration 1277 ms by bot id=6443979698
2024-02-12 06:49:55,865 INFO Update id=471136463 is handled. Duration 48 ms by bot id=6443979698
2024-02-12 06:49:59,739 INFO Update id=471136464 is handled. Duration 40 ms by bot id=6443979698
2024-02-12 06:50:04,449 INFO Update id=471136465 is handled. Duration 38 ms by bot id=6443979698
2024-02-12 06:50:09,639 INFO Update id=471136466 is handled. Duration 1359 ms by bot id=6443979698
2024-02-12 06:50:11,373 ERROR RETRY [Errno 113] Connect call failed ('172.18.0.3', 5432)
Traceback (most recent call last):
  File "/bot/core/database/functions.py", line 18, in newfn
    return await func(*args, **kwargs)
  File "/bot/core/handlers/admin_handl.py", line 96, in get_files
    files_and_types = await get_watch_files_watch(watch_id)
  File "/bot/core/database/functions.py", line 271, in get_watch_files_watch
    res = await session.execute(query)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 455, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 200, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 941, in connect
    await_only(creator_fn(*arg, **kw)),
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 130, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 195, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('172.18.0.3', 5432)
2024-02-12 06:50:12,760 INFO Update id=471136467 is handled. Duration 1864 ms by bot id=6443979698
2024-02-12 06:50:16,388 INFO Update id=471136468 is handled. Duration 1341 ms by bot id=6443979698
2024-02-12 06:50:29,818 INFO Update id=471136469 is handled. Duration 1338 ms by bot id=6443979698
2024-02-12 06:50:31,870 INFO Update id=471136470 is handled. Duration 589 ms by bot id=6443979698
2024-02-12 06:50:33,170 INFO Update id=471136471 is handled. Duration 164 ms by bot id=6443979698
2024-02-12 06:50:34,507 INFO Update id=471136472 is handled. Duration 182 ms by bot id=6443979698
2024-02-12 06:50:39,082 INFO Update id=471136473 is handled. Duration 1139 ms by bot id=6443979698
2024-02-12 06:50:45,569 INFO Update id=471136474 is handled. Duration 5305 ms by bot id=6443979698
2024-02-12 06:58:49,608 INFO commands
2024-02-12 06:58:49,887 INFO Start polling
2024-02-12 06:58:49,895 INFO Run polling for bot @Develop4581_bot id=6443979698 - 'For_develop'
2024-02-12 07:00:36,719 INFO Update id=471136475 is handled. Duration 1323 ms by bot id=6443979698
2024-02-12 07:00:46,050 INFO Update id=471136476 is handled. Duration 96 ms by bot id=6443979698
2024-02-12 07:00:48,508 INFO Update id=471136477 is handled. Duration 125 ms by bot id=6443979698
2024-02-12 07:00:50,495 INFO Update id=471136478 is handled. Duration 280 ms by bot id=6443979698
2024-02-12 07:00:55,908 INFO Update id=471136479 is handled. Duration 1399 ms by bot id=6443979698
2024-02-12 07:00:57,702 INFO Update id=471136480 is handled. Duration 413 ms by bot id=6443979698
2024-02-12 07:01:03,221 INFO Update id=471136481 is handled. Duration 1693 ms by bot id=6443979698
2024-02-12 07:01:06,379 INFO Update id=471136482 is handled. Duration 1814 ms by bot id=6443979698
2024-02-12 07:01:07,795 INFO Update id=471136483 is handled. Duration 204 ms by bot id=6443979698
2024-02-12 07:01:09,172 INFO Update id=471136484 is handled. Duration 189 ms by bot id=6443979698
2024-02-12 07:01:13,840 INFO Update id=471136485 is handled. Duration 1183 ms by bot id=6443979698
2024-02-12 07:03:04,162 INFO Update id=471136486 is handled. Duration 109177 ms by bot id=6443979698
2024-02-12 08:18:37,296 INFO Update id=471136487 is handled. Duration 1232 ms by bot id=6443979698
2024-02-12 08:18:54,147 INFO Update id=471136488 is handled. Duration 1177 ms by bot id=6443979698
2024-02-12 08:18:59,600 INFO Update id=471136489 is handled. Duration 1177 ms by bot id=6443979698
2024-02-12 08:19:01,900 INFO Update id=471136490 is handled. Duration 203 ms by bot id=6443979698
2024-02-12 08:19:04,150 INFO Update id=471136491 is handled. Duration 32 ms by bot id=6443979698
2024-02-12 08:19:05,082 INFO Update id=471136492 is handled. Duration 34 ms by bot id=6443979698
2024-02-12 08:19:08,076 INFO Update id=471136493 is handled. Duration 416 ms by bot id=6443979698
2024-02-12 08:19:13,441 INFO Update id=471136494 is not handled. Duration 4 ms by bot id=6443979698
2024-02-12 08:19:20,941 INFO Update id=471136495 is handled. Duration 1560 ms by bot id=6443979698
2024-02-12 08:19:25,142 INFO Update id=471136496 is handled. Duration 1553 ms by bot id=6443979698
2024-02-12 08:19:28,928 INFO Update id=471136497 is handled. Duration 1473 ms by bot id=6443979698
2024-02-12 08:19:40,162 INFO Update id=471136498 is handled. Duration 381 ms by bot id=6443979698
2024-02-12 08:19:41,372 INFO Update id=471136499 is handled. Duration 54 ms by bot id=6443979698
2024-02-12 08:19:44,004 INFO Update id=471136500 is handled. Duration 1145 ms by bot id=6443979698
2024-02-12 08:22:10,116 INFO Update id=471136501 is handled. Duration 144218 ms by bot id=6443979698
2024-02-12 08:23:27,119 INFO Update id=471136502 is handled. Duration 1276 ms by bot id=6443979698
2024-02-12 08:23:56,099 INFO Update id=471136503 is handled. Duration 1374 ms by bot id=6443979698
2024-02-12 08:24:14,195 INFO Update id=471136504 is handled. Duration 3329 ms by bot id=6443979698
2024-02-12 08:24:23,158 INFO Update id=471136505 is handled. Duration 1258 ms by bot id=6443979698
2024-02-12 08:24:29,642 INFO Update id=471136506 is handled. Duration 1198 ms by bot id=6443979698
2024-02-12 08:24:40,399 INFO Update id=471136507 is handled. Duration 1448 ms by bot id=6443979698
2024-02-12 08:24:44,921 INFO Update id=471136508 is handled. Duration 1188 ms by bot id=6443979698
2024-02-12 08:24:56,837 INFO Update id=471136509 is handled. Duration 1182 ms by bot id=6443979698
2024-02-12 08:25:07,590 INFO Update id=471136510 is handled. Duration 52 ms by bot id=6443979698
2024-02-12 08:25:12,228 INFO Update id=471136511 is handled. Duration 157 ms by bot id=6443979698
2024-02-12 08:25:12,976 INFO Update id=471136512 is handled. Duration 78 ms by bot id=6443979698
2024-02-12 08:25:17,049 INFO Update id=471136513 is handled. Duration 1430 ms by bot id=6443979698
2024-02-12 08:25:22,098 INFO Update id=471136514 is handled. Duration 1445 ms by bot id=6443979698
2024-02-12 08:25:37,099 INFO Update id=471136515 is handled. Duration 1567 ms by bot id=6443979698
2024-02-12 08:25:42,176 INFO Update id=471136516 is handled. Duration 1711 ms by bot id=6443979698
2024-02-12 08:25:43,838 INFO Update id=471136517 is handled. Duration 224 ms by bot id=6443979698
2024-02-12 08:25:45,327 INFO Update id=471136518 is handled. Duration 227 ms by bot id=6443979698
2024-02-12 08:25:57,317 INFO Update id=471136519 is handled. Duration 1148 ms by bot id=6443979698
2024-02-12 08:32:14,988 INFO Update id=471136520 is handled. Duration 375661 ms by bot id=6443979698
2024-02-12 08:34:25,297 INFO Update id=471136521 is not handled. Duration 4 ms by bot id=6443979698
2024-02-12 08:34:34,311 INFO Update id=471136522 is not handled. Duration 7 ms by bot id=6443979698
2024-02-12 08:34:34,312 INFO Update id=471136523 is not handled. Duration 7 ms by bot id=6443979698
2024-02-12 08:34:42,113 INFO Update id=471136524 is handled. Duration 1240 ms by bot id=6443979698
2024-02-12 08:34:54,976 INFO Update id=471136525 is handled. Duration 160 ms by bot id=6443979698
2024-02-12 08:34:55,991 INFO Update id=471136526 is handled. Duration 1175 ms by bot id=6443979698
2024-02-12 08:34:59,890 INFO Update id=471136527 is handled. Duration 37 ms by bot id=6443979698
2024-02-12 08:35:03,772 INFO Update id=471136528 is handled. Duration 34 ms by bot id=6443979698
2024-02-12 08:35:05,165 INFO Update id=471136529 is handled. Duration 40 ms by bot id=6443979698
2024-02-12 08:35:08,041 INFO Update id=471136530 is handled. Duration 54 ms by bot id=6443979698
2024-02-12 08:35:12,072 INFO Update id=471136531 is handled. Duration 1742 ms by bot id=6443979698
2024-02-12 08:35:18,529 INFO Update id=471136532 is handled. Duration 1573 ms by bot id=6443979698
2024-02-12 08:36:31,361 INFO Update id=471136533 is handled. Duration 1540 ms by bot id=6443979698
2024-02-12 08:36:36,739 INFO Update id=471136534 is handled. Duration 1503 ms by bot id=6443979698
2024-02-12 08:36:43,481 INFO Update id=471136535 is handled. Duration 148 ms by bot id=6443979698
2024-02-12 08:36:44,820 INFO Update id=471136536 is handled. Duration 82 ms by bot id=6443979698
2024-02-12 08:36:53,135 INFO Update id=471136537 is handled. Duration 1171 ms by bot id=6443979698
2024-02-12 08:37:00,461 ERROR RETRY [Errno 113] Connect call failed ('172.18.0.3', 5432)
Traceback (most recent call last):
  File "/bot/core/database/functions.py", line 18, in newfn
    return await func(*args, **kwargs)
  File "/bot/core/database/functions.py", line 179, in get_watch_id
    res = await session.execute(query)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 455, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 200, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 903, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 941, in connect
    await_only(creator_fn(*arg, **kw)),
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 130, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 195, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('172.18.0.3', 5432)
2024-02-12 08:38:10,886 INFO Update id=471136538 is handled. Duration 76638 ms by bot id=6443979698
2024-02-12 08:38:29,783 INFO Update id=471136539 is handled. Duration 310 ms by bot id=6443979698
2024-02-12 08:38:33,664 INFO Update id=471136540 is handled. Duration 385 ms by bot id=6443979698
2024-02-12 08:39:31,570 INFO Update id=471136541 is handled. Duration 1161 ms by bot id=6443979698
2024-02-12 08:39:37,518 INFO Update id=471136542 is handled. Duration 1357 ms by bot id=6443979698
2024-02-12 14:18:31,811 INFO Update id=471136543 is handled. Duration 1808 ms by bot id=6443979698
2024-02-12 14:19:04,220 INFO Update id=471136544 is handled. Duration 3399 ms by bot id=6443979698
2024-02-12 14:20:20,768 INFO Update id=471136546 is handled. Duration 154 ms by bot id=6443979698
2024-02-12 14:20:25,154 INFO Update id=471136545 is handled. Duration 15580 ms by bot id=6443979698
2024-02-12 14:20:28,299 INFO Update id=471136547 is handled. Duration 109 ms by bot id=6443979698
2024-02-12 14:20:38,748 INFO Update id=471136548 is handled. Duration 79 ms by bot id=6443979698
2024-02-12 14:20:41,314 INFO Update id=471136549 is handled. Duration 146 ms by bot id=6443979698
2024-02-12 14:20:51,867 INFO Update id=471136550 is handled. Duration 697 ms by bot id=6443979698
2024-02-12 14:21:37,757 INFO Update id=471136551 is handled. Duration 2841 ms by bot id=6443979698
2024-02-12 14:22:16,366 INFO Update id=471136552 is handled. Duration 1566 ms by bot id=6443979698
2024-02-12 14:22:35,791 INFO Update id=471136553 is handled. Duration 1676 ms by bot id=6443979698
2024-02-12 14:22:49,101 INFO Update id=471136554 is handled. Duration 230 ms by bot id=6443979698
2024-02-12 14:22:51,318 INFO Update id=471136555 is handled. Duration 166 ms by bot id=6443979698
2024-02-12 14:23:21,828 INFO Update id=471136556 is handled. Duration 1227 ms by bot id=6443979698
2024-02-12 14:29:41,450 INFO Update id=471136557 is handled. Duration 366790 ms by bot id=6443979698
2024-02-12 14:30:11,670 INFO Update id=471136558 is handled. Duration 1601 ms by bot id=6443979698
2024-02-12 14:30:17,404 INFO Update id=471136559 is handled. Duration 1963 ms by bot id=6443979698
2024-02-12 14:30:19,612 INFO Update id=471136560 is handled. Duration 247 ms by bot id=6443979698
2024-02-12 14:30:21,537 INFO Update id=471136561 is handled. Duration 163 ms by bot id=6443979698
2024-02-12 14:30:27,270 INFO Update id=471136562 is handled. Duration 3437 ms by bot id=6443979698
2024-02-12 14:31:10,769 INFO Update id=471136563 is handled. Duration 40868 ms by bot id=6443979698
2024-02-13 13:39:32,040 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 13:39:32,040 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 13:39:43,059 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:03:06,333 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:03:06,334 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:03:17,352 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:03:17,354 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:03:17,354 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:03:28,374 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:50:11,713 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:50:11,713 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:50:22,734 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:54:02,992 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:54:02,992 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:54:14,017 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 15:59:04,171 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 15:59:04,171 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 15:59:15,189 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:02:15,295 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:02:15,295 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:02:26,313 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:10:06,588 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:10:06,589 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:10:17,622 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:14:17,909 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:14:17,909 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:14:28,929 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-13 16:22:09,303 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-13 16:22:09,303 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-13 16:22:20,479 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 09:42:19,095 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 09:42:19,095 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 09:42:30,115 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:15:50,250 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:15:50,250 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:16:01,265 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:18:21,330 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:18:21,331 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:18:32,510 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:18:32,512 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:18:32,512 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:18:43,529 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:20:33,607 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:20:33,607 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:20:44,624 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:22:04,742 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:22:04,742 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:22:15,759 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:23:45,842 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:23:45,842 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:23:56,864 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:25:36,973 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:25:36,973 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:25:47,987 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:25:47,989 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:25:47,989 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:25:59,008 INFO Connection established (tryings = 1, bot id = 6443979698)
2024-02-14 13:27:19,498 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-02-14 13:27:19,498 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6443979698)
2024-02-14 13:27:30,522 INFO Connection established (tryings = 1, bot id = 6443979698)
